spring.application.name=tp1-api
# Configuración con H2 para desarrollo local sin Docker
spring.datasource.url=jdbc:h2:mem:backend_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web de H2 (opcional, para ver las tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway y JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true